language: python

python:
- 3.5
- 3.6

install:
- pip install flake8
- pip install mypy lxml

script:
- flake8 .
- mypy -p n0library

notifications:
  slack:
    secure: O0RUQY2jyVR+iHBjhcK5uxJzedZUb1dLCEoIU+4Hum9I+l1eTaVVW2DvFxFgq+OTifmFylm0doV23LVYXxXflwBmE3EFFhrDkk7kFcHIiDoJ28vlsN3qQ1SwaOjfH1RUz8mCSGZ0rb02pzWMDBS9tMxcD55M2X0+49pRDp1ubFONgy/wH+DhZmwMQ/TwFXO1+u6wMRntAqH6m5ilLwIStA/upjI3pK1sJ3P+00mygd90Qtma35/5jF8Ha10v+6XIg+shHJpCYN7O0xmIOFgxTCtxZ3tD61TnCOrPE8WossNAFZlqqveiC//zPPrRyzkd3TZLbxBVz0fLflKk63B9fNVko/5zMtjlKioYhTOwJJQ6K8Spl6Hh+h7JvQ9fy1cAsdyOpw7DisYRfzL+sYJ9jKFBD0DLCdDsRfhlOdLuf0wQGNpX3vKGJpFXT/ECzKZP1ccwIGSlbSpat3Z71prTTOGUAzWJYh6gK6swMfYbdbyHzgBhtW7QHb66DuKkTtGtF+cNc0bw/IIQiRFQQKKEo6FxIfHZq5d0gEHnBTica/1RWnRswOcuFUbxnVJ6waSTeV0Z9fMfG3dxCG1pUbI/1WkT5fGevXjzdLdtECS0i6VasdiEtnH0KQppiq7UvP0Kb7s2V1p8L00c7+G0IT37LUziUyY5U5W+W6OLcRphfTs=
